### ISSUE TITLE
Revise Description text

### ISSUE THREAD

**Issue by kintopp** [culturesofknowledge/emplaces#15]
Check RDF mapping and revise description text.

**Comment by kintopp** [comment]
Updated `em:editorialNote` on my local branch. @gklyne where is the Source for the note stored?

**Comment by kintopp** [comment]
Changed to

```
 em:editorialNote """
        Opole is a city located in southern Poland on the Oder River (Odra). With a population of approximately 127,792 (January 2017), it is the capital of the Opole Voivodeship and also the seat of Opole County. With it long history dating back to the 9th century, Opole is considered to be one of the oldest towns in Poland.
        """ ;
```

BTW, why the triple quotes?

**Comment by gklyne** [comment]
(1) it's a literal within the RDF graph.

(2) In Turtle, triple quotes `"""` indicate a literal that may extend over multiple lines, and which may contain individual quotes `"` without escaping.
