### ISSUE TITLE
Discussion: Toponyms

### ISSUE THREAD

**Issue by kintopp** [culturesofknowledge/emplaces#2]
At present we import the full list of alternative names (toponyms) from GeoNames for indexing. Only a subset should be displayed:

> For example, while we can allow users to search for and find places using a Persian transliteration of a place (Opole: اوپوله) there is no need to display this particular transliteration in the list of alternative names. For the display list, alternative names will be drawn from a short list of major European languages and historical forms (i.e. Latin). Next, the list of alternative names will be compared with one or more additional gazetteers. From this these lists, a merged set of unique alternative names will finally be shown. This is to avoid having to list multiple, identical instances of e.g. 'Opole' for the many language transliterations supported by GeoNames.

For the purposes of the sample Opele RDF, we can define this manually. Later, both for bulk imports and when adding single records, we'll need to provide a rule.

**Comment by gklyne** [comment]
I've already added `em:displayName` values to the definition for "City of Opole".  I haven't yet added anything for the various ADMx or PCLI (country) entities.

The plan is to select names during GeoNames data wrangling.

I think the plan we discussed is to use a defined list of language codes, strip the language codes, then deduplicate the resulting list of bare name strings.  I would need a list of language codes to select on.

**Comment by kintopp** [comment]
Could we consider this alternative: display all toponyms except duplicates for which we keep a single instance. In this way, we don't appear parochial for deciding for some future researcher that e.g. we don't need to include Arabic or Chinese etc in our list.

**Comment by gklyne** [comment]
There are two, maybe three, issues here:

(1) the mechanism for displaying a subset of names, and

(2) the policy for selecting which subset to display.

(3) keeping the data-selection mechanism and policy issues separate from Timbuctoo implementation (or not).

The concern I have is that if we need the selection to be dynamic (e.g. per researcher preference), then it really needs to be implemented in Timbuctoo (and the data model may well need updating to support this).

Another concern I have is: if different languages (and scripts) are involved, how do we know what are duplicates?

I note that the full set of alternative names is still in the data.  I could see the `em:displayName` values being a temporary workaround until we settle on a more flexible long-term solution?

**Comment by kintopp** [comment]
As a partial answer (though I know we mooted this at some point in the past) I don't think we should accommodate per-researcher display options. I couldn't follow your concern about finding duplicates of the actual toponym (i.e. language duplicates are fine). That is, "ABC" (en) and "DEF" (end) would count as two distinct entries and would be displayed. If either also appeared in another language it would make no difference – ABC and DEF would still only appear once on the list.

**Comment by gklyne** [comment]
Simple example:

    em:alternateName "Opole"@es ;
    em:alternateName "Opole"@nl ;

I'd assume this would be displayed just once.

Then there's:

    em:alternateName "Ополе"@bg ;
    em:alternateName "Ополе"@ru ;

or:

    em:alternateName "اوپول"@pnb ;
    em:alternateName "اوپوله"@fa ;

The last two look quite similar in my text editor view of the source data, identical in the GitHub editing view in my Firefox browser, but rather different in the GitHub preview.

And there are various "normal forms" for representing composite glyphs.

My point is: when we depart from latin-based scripts, it is harder to reliably decide what is a duplicate.  This isn't of itself an argument for not doing as you suggest, just pointing out that things could get more complicated

We could just try not selecting based on language, but deduplicating literal forms based on unicode code point sequence - I think that would be worth trying and reviewing later.  It could be handled in the data wrangling phase, which would address my separated concerns.

**Comment by kintopp** [comment]
In the first two cases, yes – one example of "Opole" and "Ополе" since they're identical. In the last example (Punjabi and Persian) these are orthographically distinct so would be listed separately. But wouldn't you rely on a UTF8-savvy script to determine equivalence or difference?

**Comment by gklyne** [comment]
For information:  I've just implemented the deduplicated Unicode sequence option for Opole.  This is what I'm getting:

    Uopole
    Горад
    Аполе
    오폴레
    Opolí
    أبولوسكي
    Ополе
    Opole
    ออปอเล
    אופולה
    Oppein
    奥波莱
    اوپوله
    オポーレ
    اوپول
    Òpòle
    Oppeln
    Opolė

**Comment by kintopp** [comment]
Matches the source data but for one small bug: "Uopole Горад" is two words, not two separate toponyms. 

Will it be possible (this is definitely a 'nice to have but not required') to hold onto the language codes after import, so that if e.g. a user holds their mouse pointer over a toponym, the language code(s) using that toponym can appear in a pop-up?

**Comment by kintopp** [comment]
I was thinking of all of them. In this way, mousing over "Opele" would reveal a tooltip label with something like "en, de, fr, it, es, nl". The trouble is, as even this example shows, that the list can get long for the most common alternatives. Let's just park the thought for now. It's a very minor point as we'll in any case make it easy for people to go to review the original GeoNames record.

**Comment by gklyne** [comment]
Re "Горад Аполе":

Interestingly, "Аполе" alone seems to denote "Opole".  And "Горад Аполе" seems to be something like "City of Opole".   Inferred from Google searches, for what it's worth.

**Comment by gklyne** [comment]
Can we close this issue yet?
