### ISSUE TITLE
EMPlaces vocabulary namespace URIs

### ISSUE THREAD

**Issue by gklyne** [culturesofknowledge/emplaces#29]
This relates to issue #6, but is different, hence a separate issue. This is about the vocabulary terms used by the data model rather than the identifiers assigned to places themselves.  There is a little overlap in areas like time period identifiers, etc.

For reference, see https://github.com/culturesofknowledge/emplaces/blob/master/models/20180802-opole-example-multisourced.ttl#L26:

    @prefix em:         <http://emplaces.namespace.example.org/> .   #@@@@ TBD
    @prefix emt:        <http://emplaces.namespace.example.org/timespan/> .
    @prefix eml:        <http://emplaces.namespace.example.org/language/> .
    @prefix ems:        <http://emplaces.namespace.example.org/source/> .

And there's this, which will be updated based on the resolution of issue #6:

    @prefix ex:         <http://emplaces.data.example.org/> .        #@@@@ TBD

I've been using placeholder namespace URIs in `example.org` domain for:

- `em:` general vocabulary terms
- `emt:` predefined time period identifiers; specifically `emt:Current`
- `eml:` language identifiers; this might be replaced by an existing vocabulary (e.g., `lexvo`?)
- `ems:` predefined source/authority identifiers; currently only `ems:EMPlaces` defined, to represent material under EMPlaces editorial control.  (Related: do we want to distinguish EMLO here?)

So the issue is: what domain to use for these.  Possible options are:

- `earlymodern.org` (or whatever domain has been registered for this project).  Are we confident that the registration will be maintained long-term?  Dereferencability is desirable but not essential.
- `vocab.ox.ac.uk` - (a) creates a possible perception of being Oxford-centric; (b) what to we know about the current state of the commitment (by the Bodleian/university) to keep this live in the long term?
- `purl.org` - has had some problems, but is widely used and I assume there's a lot of motivation out there to keep it going.
- `doi.org` - we could allocate this via Zenodo as a Datacite URI, and publish the ontologies in GitHub (I've done something similar fort Annalist software: e.g. https://doi.org/10.5281/zenodo.594496
- Others?  (I haven't listed ARK, as this seems to be a different use-case.)

I lean towards using a Datacite DOI for these, as there's a lot of community support behind these, and treating the ontology as a data publication seems about right, and hopefully these will tie in to long-term preservation strategies.  The downside is that I'm not sure if we can content-negotiate a DOI to directly retrieve an RDFS/OWL ontology - it usually ends up on a splash-page.

**Comment by kintopp** [comment]
Since these will be relevant for early modern people, places, and dates (and possibly more in the future) I assume we'll want to use (as you've suggested above) a broad or even generic domain (rather than emplaces.info). Oxford centric is not a dealbreaker, but better avoided. I previously acquired earlymodern.net as a hold-all for these kinds of resources. Given that, this reduces my preferred options to either using a doi.org via Zenodo or earlymodern.net. Probably the former is better.

**Comment by kintopp** [comment]
We've provisionally resolved this by selecting https://emplaces.info as the domain for the namespace (and subsequently, as part of the ARK IDs.). CofK owns emplaces.info, empeople,info and emdates.info. I'll close this issue for now.
